apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-job-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-job-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods/log
  - pods/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-job-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-job-manager
subjects:
- kind: ServiceAccount
  name: k8s-job-manager
  namespace: default
