apiVersion: v1
kind: Secret
metadata:
  name: k8s-job-manager
type: Opaque
stringData:
  token: do_not_use_in_production
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-job-manager
  labels:
    app: k8s-job-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: k8s-job-manager
  template:
    metadata:
      labels:
        app: k8s-job-manager
    spec:
      containers:
      - name: k8s-job-manager
        image: 52north/pygeoapi-k8s-manager:local
        imagePullPolicy: IfNotPresent
        env:
        - name: PYGEOAPI_K8S_MANAGER_NAMESPACE
          value: default
        - name: PYGEOAPI_K8S_MANAGER_API_TOKEN
          valueFrom:
            secretKeyRef:
              name: k8s-job-manager
              key: token
          #
          # configure log finalizer
          #
        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_ENDPOINT
          value: http://minio.default.svc.cluster.local:9000
        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_KEY
          value: minio_admin
        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_SECRET
          value: minio_admin
        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_NAME
          value: test-bucket
        - name: PYGEOAPI_K8S_MANAGER_FINALIZER_BUCKET_PATH_PREFIX
          value: k8s-manager/logs/
          #
          # end of log finalizer
          #
          # pyGeoAPI
          # the config, that defines the ingest API set-up
        - name: PYGEOAPI_CONFIG
          value: "/pygeoapi/local.config.yml"
          # gunicorn
        - name: CONTAINER_NAME
          value: "k8s-job-manager"
        - name: CONTAINER_PORT
          value: "80"
          # ingest
          # Keep in sync with ingress!
        - name: SCRIPT_NAME
          value: "/pygeoapi/"
        - name: WSGI_WORKERS
          value: "4"
        - name: WSGI_WORKER_TIMEOUT
          value: "6000"
        - name: WSGI_WORKER_CLASS
          value: "gevent"
        resources:
          # adjust asap to your set-up
          requests:
            memory: "512M"
            cpu: "100m"
          limits:
            memory: "768M"
            cpu: "250m"
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config
          mountPath: /pygeoapi/local.config.yml
          subPath: local.config.yml
      volumes:
      - name: config
        configMap:
          name: k8s-job-manager-config
      restartPolicy: Always
      serviceAccountName: k8s-job-manager
---
apiVersion: v1
kind: Service
metadata:
  name: k8s-job-manager
  labels:
    app: k8s-job-manager
spec:
  type: NodePort
  selector:
    app: k8s-job-manager
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: k8s-job-manager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-job-manager
rules:
- apiGroups:
  - ""
  resources:
  - events
  - pods/log
  - pods/status
  verbs:
  - get
  - watch
  - list
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
  - patch
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-job-manager
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: k8s-job-manager
subjects:
- kind: ServiceAccount
  name: k8s-job-manager
  namespace: default
