apiVersion: v1
kind: Secret
metadata:
  name: minio-credentials
type: Opaque
stringData:
  MINIO_ROOT_USER: minio_admin
  MINIO_ROOT_PASSWORD: minio_admin
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
      - name: minio
        image: quay.io/minio/minio:latest
        args:
          - server
          - /data
          - --console-address
          - ":9001"
        envFrom:
          - secretRef:
              name: minio-credentials
        ports:
          - containerPort: 9000
          - containerPort: 9001
        volumeMounts:
          - name: data
            mountPath: /data
        resources:
          # adjust asap to your set-up
          requests:
            memory: "512M"
            cpu: "100m"
          limits:
            memory: "768M"
            cpu: "250m"
      volumes:
        - name: data
          emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: minio
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9000
      targetPort: 9000
      nodePort: 30090
    - name: console
      port: 9001
      targetPort: 9001
      nodePort: 30100
---
apiVersion: batch/v1
kind: Job
metadata:
  name: minio-bucket-init
spec:
  backoffLimit: 0
  parallelism: 1
  ttlSecondsAfterFinished: 300
  template:
    spec:
      initContainers:
      - name: wait-for-minio
        image: busybox
        command: ['sh', '-c', 'until nc -z minio 9000; do date; echo waiting for minio; sleep 5; done;']
      containers:
      - name: create-bucket-and-path
        image: minio/mc
        env:
        - name: MINIO_ACCESS_KEY
          value: minio_admin
        - name: MINIO_SECRET_KEY
          value: minio_admin
        - name: MC_HOST_minio
          value: "http://<MINIO_ACCESS_KEY>:<MINIO_SECRET_KEY>@minio:9000"
        command: ["/bin/sh", "-c"]
        args:
          - |
            mc alias set myminio http://minio:9000 "$MINIO_ACCESS_KEY" "$MINIO_SECRET_KEY"
            mc mb --ignore-existing myminio/test-bucket
            echo "init" | mc pipe myminio/test-bucket/k8s-manager/logs/init.txt
        resources:
          requests:
            memory: "16M"
            cpu: "25m"
          limits:
            memory: "16M"
            cpu: "25m"
      restartPolicy: Never
